# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: SSH Remote Command
      uses: appleboy/ssh-action@master
      with:
        # ssh host
        host: 103.82.21.88
        # ssh username
        username: root
        # ssh password
        password: @U#)*&3qE66)q7o#
        script:
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
    - run: npm i
