# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_SSH}}

          script: |
            cd /var/www/quizz_server/quizz_server
            npm i


# name: Node.js CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
    
#     - run: git pull
#     - run: npm i
#     - run: pm2 list
#     - run: pm2 stop 0
#     - run: pm2 start 0
#     - run: pm2 save
#     - run: sudo service nginx restart
