# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          key: ${{secrets.SERVER_SSH}}

          script: |
            cd /var/www/quizz_server/quizz_server
            git pull
            pm2 restart 0
